---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: edia-sns-java-sample-consumer
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: sns-consumer.edia-tst.eu
    http:
      paths:
      - path: /
        backend:
          serviceName: edia-sns-java-sample
          servicePort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: edia-sns-java-sample-producer
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: sns-producer.edia-tst.eu
      http:
        paths:
          - path: /
            backend:
              serviceName: edia-sns-java-sample
              servicePort: 8080
